<?php

namespace AppBundle\Repository;

/**
 * DeviceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
