<?php

namespace AppBundle\Repository;

/**
 * HospitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospitalRepository extends \Doctrine\ORM\EntityRepository
{
}
